export enum NotificationType {
  // Trip lifecycle
  TRIP_CREATED = 'TRIP_CREATED',
  TRIP_STARTED = 'TRIP_STARTED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  TRIP_CANCELLED = 'TRIP_CANCELLED',
  TRIP_BROADCAST_LOCKED = 'TRIP_BROADCAST_LOCKED',
  TRIP_BROADCAST_RELEASED = 'TRIP_BROADCAST_RELEASED',
  TRIP_HANDED_OFF = 'TRIP_HANDED_OFF',
  TRIP_DISPUTED = 'TRIP_DISPUTED',

  // Delivery lifecycle
  DELIVERY_CREATED = 'DELIVERY_CREATED',
  DELIVERY_PICKED_UP = 'DELIVERY_PICKED_UP',
  DELIVERY_DELIVERED = 'DELIVERY_DELIVERED',
  DELIVERY_ATTEMPT_FAILED = 'DELIVERY_ATTEMPT_FAILED',
  DELIVERY_RETURNED = 'DELIVERY_RETURNED',
  DELIVERY_CANCELLED = 'DELIVERY_CANCELLED',

  // Matching
  RIDER_OFFER_DISPATCHED = 'RIDER_OFFER_DISPATCHED',

  // Direct / ad-hoc
  DIRECT_EMAIL = 'DIRECT_EMAIL',
  DIRECT_SMS = 'DIRECT_SMS',
}
