export enum FailureReason {
  RECIPIENT_NOT_HOME = 'RECIPIENT_NOT_HOME',
  WRONG_ADDRESS = 'WRONG_ADDRESS',
  REFUSED_DELIVERY = 'REFUSED_DELIVERY',
  INACCESSIBLE_LOCATION = 'INACCESSIBLE_LOCATION',
  WEATHER_CONDITIONS = 'WEATHER_CONDITIONS',
  OTHER = 'OTHER',
}
