import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { DomainExceptionFilter } from './inflastructure/filters/domain-exception.filter';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalFilters(new DomainExceptionFilter());
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  const config = new DocumentBuilder()
    .setTitle('User Service')
    .setDescription(
      `Owns rider/passenger accounts, authentication and rider profiles for the Courier platform.

## Getting started

1. **Register**: \`POST /users\` with first/last name, email, gender, national ID and password.
2. **Log in**: \`POST /users/login\` with email + password to receive a JWT \`accessToken\`.
3. **Authorize**: click the **Authorize** button above and paste the token as \`Bearer <accessToken>\` — every endpoint marked with a lock icon needs it.
4. **Become a rider**: once logged in, \`POST /riders\` (with the JWT) to register as a courier and add vehicles.

## Notes for consumers

- IDs are UUID strings generated by the service — store the \`id\` returned from \`POST /users\`/\`POST /riders\` for later calls.
- \`GET /users/me\` resolves the current user from the JWT — prefer it over \`GET /users/:id\` when you only need "my" profile.
- Other services (trip-service, matching-service, delivery-service) call this service internally over HTTP at \`http://user-service:3001\` to validate users and look up rider availability/vehicles.`,
    )
    .setVersion('1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Paste the JWT returned by POST /users/login' },
      'access-token',
    )
    .addTag('users', 'Account creation, authentication and profile management')
    .addTag('riders', 'Rider (courier) profiles and vehicles')
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api/docs', app, document, {
    swaggerOptions: { persistAuthorization: true },
  });

  await app.listen(process.env.PORT ?? 3000);
}
bootstrap();
